"""add users table

Revision ID: 02a3bb8d0370
Revises: b09012071ea0
Create Date: 2026-08-17 08:57:35.914436

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "02a3bb8d0370"
down_revision: Union[str, Sequence[str], None] = "b09012071ea0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("photo_url", sa.String(), nullable=False),
        sa.Column(
            "auth_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.alter_column(
        "transactions",
        "user_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    
    op.execute("""
        INSERT INTO users (user_id, username, first_name, photo_url)
        SELECT DISTINCT
            user_id,
            'unknown_' || user_id::text,
            'Unknown',
            ''
        FROM transactions
        WHERE user_id IS NOT NULL
        ON CONFLICT (user_id) DO NOTHING
    """)

    op.create_foreign_key(
        "fk_transactions_user_id_users", "transactions", "users", ["user_id"], ["user_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.alter_column(
        "transactions",
        "user_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_table("users")
    # ### end Alembic commands ###
