"""rename table to transaction and add type

Revision ID: b09012071ea0
Revises: 6df258ff1f8f
Create Date: 2026-08-11 17:27:26.921530

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b09012071ea0"
down_revision: Union[str, Sequence[str], None] = "6df258ff1f8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("expenses", "transactions")
    op.add_column(
        "transactions",
        sa.Column("type", sa.String(), nullable=False, server_default="Expense"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "type")
    op.rename_table("transactions", "expenses")
    # ### end Alembic commands ###
